### ISSUE TITLE
Not correct behavior numberParser 

### ISSUE THREAD

**Issue by Leon-Alexey** [jquery/globalize#521] opened 2015-10-05 08:50 UTC
Hello!

example no correct:
.numberParser()( "" )
// > "nan"

is true:
.numberParser()( "" )
// > ""
.numberParser()( "qwerty" )
// > "nan"

locale = "ru", build 1.1.0-rc.3

**Comment by rxaviers** [comment] 2015-10-05 13:34
@Leon-Alexey, follow below what I get:

```js
Globalize('ru').numberParser()('');
// > NaN

Globalize('ru').numberParser()('qwerty');
// > NaN
```

I couldn't reproduce or understand what you mean. Both output above seems correct to me, so I'm closing this issue. Feel free to add new comments explaining what you believe is wrong or if you have any questions.

Thanks.

**Closed by rxaviers** 2015-10-05 13:34 UTC

**Comment by Leon-Alexey** [comment] 2015-10-05 13:44
if (value === '') then return Globalize('ru').numberParser()('') -> ''
nan don't need

**Comment by rxaviers** [comment] 2015-10-05 14:09
Number parser should never return a String. Also, returning `NaN` for empty Strings mimics native JavaScript behaviour `parseFloat('') // NaN`.

If you need an empty String in that case, please consider handling this at user code.

**Comment by Leon-Alexey** [comment] 2015-10-06 06:03
At the entrance is empty, then the output should be empty. The user does not enter a value, and you generate the string "nan". In the DB should be null value and not the string "nan" . After parsing, it is not clear, the input was null or not a null string. Obviously, I don't see why I should have to convince you of this. Okay, don't want what you want, what's the point of the project? if you are too lazy to do that requires business, then close the project.

**Comment by rxaviers** [comment] 2015-10-06 11:20
> and you generate the value "nan"

`NaN` is https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN. It means an empty String is not a number. You can check for empty input with `input.length`. Note, you don't need to use `numberParser` for that.

I respect your opinion. But, the library is doing the right thing.

**Comment by Leon-Alexey** [comment] 2015-10-06 11:46
I must parse to understand what you need to pass to your parser? 
Don't you think that it should be a parser function?
An empty value is not a string value and not the value of the number, empty value is nothing, the value is empty is a Null value in the database. Nan this value is a string, how should I value the string to write to the table field type number?

**Comment by rxaviers** [comment] 2015-10-06 11:50
I've done my best to explain why it works this way and I won't continue this discussion any further.

**Comment by Leon-Alexey** [comment] 2015-10-06 12:01
capitulated, it's because You're out of arguments, this means that I'm right. 
I'll have to do fork.

**Comment by jzaefferer** [comment] 2015-10-06 15:13
Look:
```js
parseInt('')
> NaN
parseFloat('')
> NaN
```
Globalize implements the same behaviour as the native, standard methods: An empty string is not a number. If you don't agree, you can implement whatever you want in your own application or library, but its not going to change this one.

**Comment by Leon-Alexey** [comment] 2015-10-07 06:45
I request that You did not write that empty string is not a number, it's obvious. 
Library and create, the javascript to fix defects. 
The data entry form, nobody entered values nothing, and in the DB a bunch of errors it has been entered incorrectly, because of some stupid parser.
