### ISSUE TITLE
Decimal separator ignored at the beginning of parsed value, e.g. ".5" is parsed as 5

### ISSUE THREAD

**Issue by kolman** [jquery/globalize#517] opened 2015-10-01 20:27 UTC
Decimal separator is ignored when the parsed value does not have leading zero:
```
Globalize('en').parseNumber('.5');
// => 5
parseFloat('.5');
// => 0.5
```

**Comment by Mottie** [comment] 2015-10-02 01:51
Duplicate of #443

**Closed** 2015-10-02 11:36 UTC

**Comment by rxaviers** [comment] 2015-10-02 11:55
Thank you @Mottie and @kolman.
