### ISSUE TITLE
Globalize 1.0.0 does not work the the latest es5-shim

### ISSUE THREAD

**Issue by Nexith** [jquery/globalize#561] opened 2015-12-03 10:25 UTC
When using ```globalize 1.0.0``` with the latest ```es5-shim``` it throws ```throws new TypeError(ERR_ACCESSORS_NOT_SUPPORTED);``` on line 55 in plural.js.

I first created an issue in the ```es5-shim``` repo, see: es-shims/es5-shim#363 for more information.

**Comment by ljharb** [comment] 2015-12-03 15:30
Note that this means globalize doesn't support IE 8, which has defineProperty but does not support defining properties on non-DOM elements.

**Comment by rxaviers** [comment] 2016-01-17 12:52
This regression has been introduced by 7e1cee3b, which updated make-plural from `2.1.2` to `3.0.0`. So, the last Globalize that was compatible with IE8 was `1.0.0-alpha.20`.

**Comment by rxaviers** [comment] 2016-01-17 13:01
FWIW, this regression should affect the plural module only.

**Comment by rxaviers** [comment] 2016-01-17 13:51
I plan a patch fix `1.0.1` that will bring back support for IE8. PR #579.

**Comment by ericelliott** [comment] 2016-01-22 10:09
Looks like that PR was merged. Should this issue be closed?

**Comment by rxaviers** [comment] 2016-01-22 10:10
Yeap, thanks

**Comment by rxaviers** [comment] 2016-01-22 10:10
`1.0.1` has been released.

**Closed by rxaviers** 2016-01-22 10:10 UTC
