### ISSUE TITLE
formatDate with custom options affect the entire application

### ISSUE THREAD

**Issue by Songissimo** [jquery/globalize#589] opened 2016-02-10 10:46 UTC
Hi everybody,
   apparently when formatDate method is called the first time wtih some custom parameters eg: formatDate('2015-02-02': {data:'short'}), those settings are retained and applied also when calling a simple formatDate('2015-02-02'), in such a way the wrong format is used for the second call.

Thanks.

**Comment by rxaviers** [comment] 2016-02-10 10:54
I could not reproduce such issue. Please, could you provide the steps you took, the globalize you're using and which environment that you noticed the problem?

In order to test, I did the below.

```
npm install globalize cldr-data
node

> var Globalize = require( "globalize" );
undefined
> Globalize.load( require( "cldr-data" ).entireSupplemental() );
undefined
> Globalize.load( require( "cldr-data" ).entireMainFor( "en", "es" ) );
undefined
> Globalize('en').formatDate(new Date(), {date: 'short'});
'2/10/16'
> Globalize('en').formatDate(new Date());
'2/10/2016'
```

PS: I assume you meant `{date: 'short'}`.

**Comment by rxaviers** [comment] 2016-02-10 10:54
I'm closing for now and will reopen when it's reproducible.

**Closed by rxaviers** 2016-02-10 10:54 UTC
