### ISSUE TITLE
Bug? Inconsistent number-format behaviour for fixed locale, depending on cldr-data loaded.

### ISSUE THREAD

**Issue by greghuc** [jquery/globalize#442] opened 2015-04-28 15:38 UTC
### Summary

I'm seeing some strange behaviour with globalize, where number-format behaviour is changing for a fixed locale, depending on what locale data I load from the [cldr-data](https://github.com/rxaviers/cldr-data-npm) package.

Specifically, I've been loading all locale data from the cldr-data package (example program below). The output of the number formatter differs depending on whether the "cldr-data-coverage": "full" flag is used.

For example, for Globalize('en').numberFormatter()(1234567.891):
- "cldr-data-coverage": "full" flag used -> 1234567.891 (which looks wrong!)
- no flag -> 1,234,567.891 (which looks correct)

I'm reporting this as a bug, as it seems very strange behaviour!

From my investigations, it's only affecting the following locales: 
['en', 'en-u-nu-native', 'en-US', 'en-US-u-nu-native', 'en-US-POSIX', 'en-US-POSIX-u-nu-native', 'root', 'root-u-nu-native']. 

I ran into this bug when I switched from using the deprecated [cldr-data-full](https://github.com/rxaviers/cldr-data-full-npm) package to [cldr-data](https://github.com/rxaviers/cldr-data-npm).

### Detail

Below is a test.js program which:
* Loads all locale data from the cldr-data package
* Runs Globalize(locale).numberFormatter(1234567.891) for different locales

It shows different output, depending on whether the "cldr-data-coverage": "full" is set or not in package.json. The output looks wrong when the flag is used.

Program output with flag used:
```
package.json
{
  ...
  "cldr-data-coverage": "full",
  "dependencies": {
    "cldr-data": "26.0.11",
    "globalize": "1.0.0"
  },
  ...
}

stdout:
Value: 1234567.891
Locale: en: 1234567.891
Locale: en-u-nu-native: 1234567.891
Locale: en-US: 1234567.891
Locale: en-US-u-nu-native: 1234567.891
Locale: en-US-POSIX: 1234567.891
Locale: en-US-POSIX-u-nu-native: 1234567.891
Locale: root: 1234567.891
Locale: root-u-nu-native: 1234567.891
```

Program output with no flag:
```
package.json:
{
  ...	
  "dependencies": {
    "cldr-data": "26.0.11",
    "globalize": "1.0.0"
  },
  ...
}

stdout:
Value: 1234567.891
Locale: en: 1,234,567.891
Locale: en-u-nu-native: 1,234,567.891
Locale: en-US: 1,234,567.891
Locale: en-US-u-nu-native: 1,234,567.891
Locale: en-US-POSIX: 1,234,567.891
Locale: en-US-POSIX-u-nu-native: 1,234,567.891
Locale: root: 1,234,567.891
Locale: root-u-nu-native: 1,234,567.891
```

test.js program:

```
Globalize = require('globalize');

Cldr = function(cldrFilePath) {
 return require('cldr-data/' + cldrFilePath);
};

var availableLocales = Cldr('availableLocales.json').availableLocales;
Globalize.load(Cldr('supplemental/likelySubtags.json'));
Globalize.load(Cldr('supplemental/numberingSystems.json'));

var i;
var locale;
for (i = 0; i < availableLocales.length; i++) {
    locale = availableLocales[i];
    Globalize.load(Cldr("main/" + locale + "/numbers.json"));
}

var formatNumberInLocale = function(value, locale) {
    return Globalize(locale).numberFormatter()(value);
};


var value = 1234567.891;

console.log('Value: ' + value);
var testLocales = ['en', 'en-u-nu-native', 'en-US', 'en-US-u-nu-native', 'en-US-POSIX', 'en-US-POSIX-u-nu-native', 'root', 'root-u-nu-native'];
for (i = 0; i < testLocales.length; i++) {
    locale = testLocales[i];
    console.log('Locale: ' + locale + ': ' + formatNumberInLocale(value, locale));
}
```

**Comment by rxaviers** [comment] 2015-04-29 02:05
Hi @greghuc, thanks for your detailed description for this issue.

https://github.com/rxaviers/cldrjs/issues/29 needs to be fixed. The problem is not handling the variant subtag `POSIX` correctly. As soon as it's fixed, I will update it on Globalize as well. It's intriguing how you made it work for the regular coverage (not the full one). For me, it fails as well.

Note you shouldn't use the `root` locale. Because, it doesn't make sense. When you request for `root`, you actually request for `und` (undefined). For more information, see https://github.com/rxaviers/ecma402-fix-lookup-matcher/issues/2.

**Comment by greghuc** [comment] 2015-04-29 08:06
Hi @rxaviers, thanks for the reply. I'm glad this is a bug and I'm not going mad!

https://github.com/rxaviers/cldrjs/issues/29 refers to a specific problem with \*-POSIX locales. If addressed, will this fix the incorrect formatting for all the locales I reported, including the more common en-* locales?

Regarding regular coverage vs full coverage, I ran test.js again, and got the same results as reported above. You might want to make sure that you _really_  have the correct version of the cldr-data package when you switch between regular and full using the flag. I went with:
```
rm -rf ./node_modules && npm cache clean && npm install
```
Thanks for explaining about ```root```. I wanted to generate formatted numbers for all locales, so I'm looping through availableLocales and running the number formatter. That's what picks ```root``` up as a locale, and that's how I could see what locale results had changed (to an incorrect value).

**Comment by rxaviers** [comment] 2015-04-29 12:19
> If addressed, will this fix the incorrect formatting for all the locales I reported, including the more common en-* locales?

It will fix them as well. Because, the "mal-handling" of `en-US-POSIX` makes `en`, `en-US`, etc to point to the wrong bundle. Instead of pointing to `en`, they point to `en-US-POSIX`:

![out-2](https://cloud.githubusercontent.com/assets/967155/7390649/a558eda8-ee50-11e4-8d6d-fbadc4dd5eba.gif)

**Comment by rxaviers** [comment] 2016-01-18 12:32
cldrjs@0.4.4 has been released with a fix for this issu.

**Closed** 2016-01-18 12:32 UTC
Labels: bug, help wanted, Quick change

**Comment by greghuc** [comment] 2016-01-18 14:34
@rxaviers thanks for the fix!

**Comment by rxaviers** [comment] 2016-01-18 15:18
:+1: ywc
