### ISSUE TITLE
Format date as day and full month

### ISSUE THREAD

**Issue by vectart** [jquery/globalize#461] opened 2015-07-14 16:08 UTC
I'm trying to format a date in German locale, so in result I have `5 Oktober`.

That works fine:
```js
.dateFormatter({ skeleton: 'Md' })(new Date('2015-10-05'))
// "5.10."
.dateFormatter({ skeleton: 'MMd' })(new Date('2015-10-05'))
// "5.10."
.dateFormatter({ skeleton: 'MMMd' })(new Date('2015-10-05'))
// "5. Okt."
```

That fails:
```js
.dateFormatter({ skeleton: 'MMMMd' })(new Date('2015-10-05'))
/*
Uncaught Error: E_UNSUPPORTED: Unsupported {"feature":"year pattern `u`"}.
    at createError (http://10.3.220.169:8002/vendor/globalize/dist/globalize.js:105:10)
    at createErrorUnsupportedFeature (http://10.3.220.169:8002/vendor/globalize/dist/globalize/number.js:52:9)
    at http://10.3.220.169:8002/vendor/globalize/dist/globalize/date.js:646:11
    at String.replace (native)
    at dateFormatProperties (http://10.3.220.169:8002/vendor/globalize/dist/globalize/date.js:604:10)
    at Globalize.dateFormatter.Globalize.dateFormatter [as dateFormatter] (http://10.3.220.169:8002/vendor/globalize/dist/globalize/date.js:1749:15)
*/
```

Nonetheless, Finnish locale gives expected result:
```js
.dateFormatter({ skeleton: 'MMMd' })(new Date('2015-10-05'))
// "5. lokakuuta"
```

How to get  `5 Oktober` in `de` locale?

**Comment by rxaviers** [comment] 2015-07-14 19:04
The correct solution is to get #271 implemented. Contribution is highly appreciated.

A workaround would be to specify the `raw` format (recommended for machine parsing only, not for your purposes though): `{raw: "d. MMMM"}`

// > '4. Oktober'

**Comment by rxaviers** [comment] 2015-08-04 17:06
Closing as duplicate of #271.

**Closed by rxaviers** 2015-08-04 17:06 UTC
