### ISSUE TITLE
tutorial

### ISSUE THREAD

**Issue by rodrigoporcionato** [jquery/globalize#468] opened 2015-07-23 00:22 UTC
Hi @rxaviers !

You not have some tutorial to use with ASP.NET MVC. I have some problems to integrate this with jquery validate in pt-BR. Se puder falar em português me ajudaria :)

**Comment by rxaviers** [comment] 2015-07-23 18:49
Hi @rodrigoporcionato, we don't have any tutorial for ASP.NET MVC using Globalize 1.x. Although, we are working towards improving our documentation + give examples using for full stack applications and we would love contribution on that front. Do you want to submit a Pull Request implementing the example? I'm not a .Net expert. But, I could help you with the Globalize part of it.

Duplicate of #358

---

Opa, não temos tutorial pro ASP.NET MVC usando o novo Globalize 1.x. Mas, estamos trabalhando pra melhorar nossa documentação + fornecer exemplos usando aplicações completas e adorariamos contribuições nesta frente. Quer enviar um Pull Request implementando o exemplo? Não manjo de .NET. Mas, posso ajudar na parte do Globalize.

**Closed by rxaviers** 2015-07-23 18:49 UTC

**Comment by jzaefferer** [comment] 2015-07-24 14:44
Since you mentioned jQuery Validation, may want to check out https://github.com/johnnyreilly/jquery-validation-globalize

As for ASP.NET MVC, this may come in handy: https://github.com/johnnyreilly/jQuery.Validation.Unobtrusive.Native

**Comment by rxaviers** [comment] 2015-07-24 14:59
Just emphasizing... The above lib supports deprecated Globalize 0.x (unless I'm missing something). But, it's an excellent additional reference. I wonder if @johnnyreilly (who has been actively involved in other issues) would be interested in updating his library to support Globalize 1.x?

**Comment by johnnyreilly** [comment] 2015-07-24 15:17
Hi @rxaviers,

Updating to 1.x has long been on my list of things to do.  Someone raised [an issue](https://github.com/johnnyreilly/jquery-validation-globalize/issues/8) about it in fact! :smile:  

I finally turned my attention to it about a month ago and after initial progress I stumbled on some difficulties and raised this issue:  https://github.com/jquery/globalize/issues/459

If you're able to take a look at it I've high hopes I'll be able to complete the migration....

**Comment by rxaviers** [comment] 2015-07-24 16:44
Hi @johnnyreilly, that's awesome. I've added a new comment on #459 and thank you for your prompt answer.
